### ISSUE TITLE
Refactorizar paquete parser

### ISSUE THREAD

**Issue by avancasielles** [Arquisoft/Loader_e4a#8]
NOTA: Este paquete ha de moficarse para permitir la lectura de ficheros CSV, posiblemente muchas cosas cambien.

* InsertR -> Refactorizar por InsertReader. Si se encuentra una mejor nomeclatura, aplicarla. Mover al paquete dbUpdate. 
* ReaderSingleton -> Refactorizar cad por path en el método loadFile.
* RList -> Refactorizar por ReadListExcel o similar.

**Comment by Llambi** [comment]
A falta de realizar algún test ya esta implementada esta parte.
